if (Misc_enabled) {
	NEI.override_invert("Backpack:backpack", [100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116]);
	NEI.hide("Baubles:Ring");
	NEI.hide("BigReactors:bucket*");
	NEI.hide("BigReactors:tile.fluid*");
	NEI.hide("BigReactors:BRDebugTool");
	NEI.hide("BigReactors:*Creative*");
	NEI.hide("CompactMachines:interface");
	NEI.hide("CompactMachines:innerwall");
	NEI.hide("GregsLighting:floodlightBeam");
	NEI.override_invert("JABBA:upgradeCore", [10]);
	NEI.override_invert("JABBA:hammer", [7]);
	NEI.override("LiquidXP:liquidxp.medallion", [0]);
	NEI.hide("StevesFactoryManager:BlockCableCreativeName");
	NEI.hide("Sync:Sync_ShellConstructor");
	NEI.hide("statues:statues.statue");
	NEI.hide("statues:statues.showcase");
	NEI.hide("TF2Dispenser:TF2DispenserInactive");
	NEI.hide("TF2Dispenser:TF2DispenserActive");
	NEI.hide("TF2Teleporter:TF2TeleporterBluBlock");
	NEI.hide("TF2Teleporter:TF2TeleporterRedBlock");
	NEI.hide("usefulDNS:Fossils");
	NEI.hide("usefulDNS:MelonGrass");
	NEI.hide("usefulDNS:FoolsGold");
	NEI.hide("usefulDNS:FoolsIron");
	NEI.hide("usefulDNS:UnobtainItem");
	NEI.hide("Aroma1997sDimension:aromicPortal");
	NEI.override("computronics:computronics.chatBox", [0]);
	NEI.override("Genetics:serum*", [0]);
	NEI.override_invert("NetherOres:tile.netherores.ore.0", [12]);
	NEI.override_invert("NetherOres:tile.netherores.ore.1", [6,8,9,10,12,15]);
	NEI.hide("NetherOres:netherOresBlockHellfish");
	NEI.hide("CarpentersBlocks:blockCarpentersBed");
	NEI.hide("CarpentersBlocks:blockCarpentersDoor");
	NEI.hide("ComputerCraft:command_computer");
	NEI.override("ComputerCraft:diskExpanded", [0]);
	NEI.hide("LogisticsPipes:logisticsPipeBlock");
	NEI.hide("StevesCarts:ModularCart");
	NEI.override_invert("StevesCarts:upgrade", [14]);
	NEI.override_invert("StevesCarts:CartModule", [61,76,72,96,97]);
	NEI.hide("OpenComputers:caseCreative");
	NEI.override_invert("OpenComputers:item", [73,81,103,91,90,69,93]); 
	NEI.hide("minechem:fluid.*");
	NEI.hide("minechem:tile.oreUranium");
	NEI.override("AgriCraft:channelValve", [0]);
	NEI.override("AgriCraft:waterChannel", [0]);
	NEI.override("AgriCraft:waterTank", [0]);
	NEI.hide("AgriCraft:debugger");
	NEI.hide("ImmersiveEngineering:ore");
	NEI.override("eng_toolbox:ore", [2]);
	NEI.hide("eng_toolbox:slickwater");
	NEI.hide("eng_toolbox:tempRS");
}