if (FML.isModLoaded("chisel")){
	NEI.override("chisel:aluminumblock", [0]);
	NEI.override("chisel:andesite", [0]);
	NEI.override("chisel:antiBlock", [0]);
	NEI.override("chisel:arcane", [0]);
	NEI.override("chisel:bloodRune", [0]);
	NEI.override("chisel:bookshelf", [1]);
	NEI.override("chisel:brickCustom", [1]);
	NEI.override("chisel:bronzeblock", [0]);
	NEI.override("chisel:carpet_block", [0]);
	NEI.override("chisel:carpet", [0]);
	NEI.override("chisel:cloud", [0]);
	NEI.override("chisel:cobblestone", [1]);
	NEI.override("chisel:mossy_cobblestone", [1]);
	NEI.override("chisel:concrete", [0]);
	NEI.override("chisel:copperblock", [0]);
	NEI.override("chisel:diamond_block", [1]);
	NEI.override("chisel:diorite", [0]);
	NEI.override("chisel:dirt", [0]);
	NEI.override("chisel:emerald_block", [1]);
	NEI.override("chisel:factoryblock*", [0]);
	NEI.override("chisel:fantasyblock*", [0]);
	NEI.override("chisel:futura", [0]);
	NEI.override("chisel:glass", [1]);
	NEI.override("chisel:glass_pane", [1]);
	NEI.override("chisel:factoryblock*", [0]);
	NEI.override("chisel:stained_glass_white", [0,4,8,12]);
	NEI.override("chisel:stained_glass_yellow", [0,4,8,12]);
	NEI.override("chisel:stained_glass_lightgray", [0,4,8,12]);
	NEI.override("chisel:stained_glass_brown", [0,4,8,12]);
	NEI.override("chisel:stained_glass_pane*", [0,8]);
	NEI.override("chisel:glowstone", [1]);
	NEI.override("chisel:gold2", [0]);
	NEI.override("chisel:gold_block", [1]);
	NEI.override("chisel:granite", [0]);
	NEI.override("chisel:grimstone", [0]);
	NEI.override("chisel:hex*", [0]);
	NEI.override("chisel:holystone", [0]);
	NEI.override("chisel:ice", [1]);
	NEI.override("chisel:ice_*", [0]);
	NEI.override("chisel:iron_bars", [1]);
	NEI.override("chisel:iron_block", [1]);
	NEI.override("chisel:iron2", [0]);
	NEI.override("chisel:laboratoryblock", [0]);
	NEI.override("chisel:lapis_block", [1]);
	NEI.override("chisel:lavastone", [0]);
	NEI.override("chisel:leadblock", [0]);
	NEI.override("chisel:leaves", [6]);
	NEI.override("chisel:limestone*", [0]);
	NEI.override("chisel:marble*", [0]);
	NEI.override("chisel:nation", [0]);
	NEI.override("chisel:rebel", [0]);
	NEI.override("chisel:nether*", [1]);
	NEI.override("chisel:obsidian", [1]);
	NEI.override("chisel:packedice", [1]);
	NEI.override("chisel:packedice_*", [0]);
	NEI.override("chisel:paperwall*", [0]);
	NEI.override("chisel:present", [0]);
	NEI.override("chisel:redstone_block", [1]);
	NEI.override("chisel:road_line", [0]);
	NEI.override("chisel:sandstone", [3]);
	NEI.override("chisel:sandstone_scribbles", [0]);
	NEI.override("chisel:silverblock", [0]);
	NEI.override("chisel:steelblock", [0]);
	NEI.override("chisel:stonebricksmooth", [0]);
	NEI.override("chisel:technical*", [0]);
	NEI.override("chisel:templeblock", [0]);
	NEI.override("chisel:mossy_templeblock", [0]);
	NEI.override("chisel:tinblock", [0]);
	NEI.override("chisel:thaumium", [0]);
	NEI.override("chisel:tyrian", [0]);
	NEI.override("chisel:uraniumblock", [0]);
	NEI.override("chisel:valentines", [0]);
	NEI.override("chisel:voidstone", [0]);
	NEI.override("chisel:voidstone2", [0]);
	NEI.override("chisel:voidstoneRunic", [1]);
	NEI.override("chisel:warningSign", [0]);
	NEI.override("chisel:waterstone", [0]);
	NEI.override("chisel:*planks", [1]);
	NEI.override("chisel:woolen_clay", [0]);
	NEI.hide("chisel:jackolantern2");
	NEI.hide("chisel:jackolantern3");
	NEI.hide("chisel:jackolantern4");
	NEI.hide("chisel:jackolantern5");
	NEI.hide("chisel:jackolantern6");
	NEI.hide("chisel:jackolantern7");
	NEI.hide("chisel:jackolantern8");
	NEI.hide("chisel:jackolantern9");
	NEI.hide("chisel:jackolantern10");
	NEI.hide("chisel:jackolantern11");
	NEI.hide("chisel:jackolantern12");
	NEI.hide("chisel:jackolantern13");
	NEI.hide("chisel:jackolantern14");
	NEI.hide("chisel:jackolantern15");
	NEI.hide("chisel:jackolantern16");
	NEI.hide("chisel:pumpkin2");
	NEI.hide("chisel:pumpkin3");
	NEI.hide("chisel:pumpkin4");
	NEI.hide("chisel:pumpkin5");
	NEI.hide("chisel:pumpkin6");
	NEI.hide("chisel:pumpkin7");
	NEI.hide("chisel:pumpkin8");
	NEI.hide("chisel:pumpkin9");
	NEI.hide("chisel:pumpkin10");
	NEI.hide("chisel:pumpkin11");
	NEI.hide("chisel:pumpkin12");
	NEI.hide("chisel:pumpkin13");
	NEI.hide("chisel:pumpkin14");
	NEI.hide("chisel:pumpkin15");
	NEI.hide("chisel:pumpkin16");
	NEI.hide("chisel:ice_stairs.1");
	NEI.hide("chisel:ice_stairs.2");
	NEI.hide("chisel:ice_stairs.3");
	NEI.hide("chisel:ice_stairs.4");
	NEI.hide("chisel:ice_stairs.5");
	NEI.hide("chisel:ice_stairs.5");
	NEI.hide("chisel:ice_stairs.6");
	NEI.hide("chisel:ice_stairs.7");
	NEI.hide("chisel:packedice_stairs.1");
	NEI.hide("chisel:packedice_stairs.2");
	NEI.hide("chisel:packedice_stairs.3");
	NEI.hide("chisel:packedice_stairs.4");
	NEI.hide("chisel:packedice_stairs.5");
	NEI.hide("chisel:packedice_stairs.5");
	NEI.hide("chisel:packedice_stairs.6");
	NEI.hide("chisel:packedice_stairs.7");
	NEI.hide("chisel:limestone_stairs.1");
	NEI.hide("chisel:limestone_stairs.2");
	NEI.hide("chisel:limestone_stairs.3");
	NEI.hide("chisel:limestone_stairs.4");
	NEI.hide("chisel:limestone_stairs.5");
	NEI.hide("chisel:limestone_stairs.5");
	NEI.hide("chisel:limestone_stairs.6");
	NEI.hide("chisel:limestone_stairs.7");
	NEI.hide("chisel:marble_stairs.1");
	NEI.hide("chisel:marble_stairs.2");
	NEI.hide("chisel:marble_stairs.3");
	NEI.hide("chisel:marble_stairs.4");
	NEI.hide("chisel:marble_stairs.5");
	NEI.hide("chisel:marble_stairs.5");
	NEI.hide("chisel:marble_stairs.6");
	NEI.hide("chisel:marble_stairs.7");	
	NEI.hide("chisel:torch2");
	NEI.hide("chisel:torch3");
	NEI.hide("chisel:torch4");
	NEI.hide("chisel:torch5");
	NEI.hide("chisel:torch5");
	NEI.hide("chisel:torch6");
	NEI.hide("chisel:torch7");
	NEI.hide("chisel:torch8");
	NEI.hide("chisel:torch9");
	NEI.hide("chisel:torch10");
	NEI.hide("chisel:amber");
	NEI.hide("chisel:bloodBrick");
}