if (FML.isModLoaded("Thaumcraft")) {
	NEI.override("Thaumcraft:ItemEssence", [0,1]);
	NEI.override("Thaumcraft:ItemWispEssence", [0]);
	NEI.override("Thaumcraft:blockTaint", [2]);
	NEI.override("Thaumcraft:blockCustomPlant", [2,3,4]);
	NEI.hide("Thaumcraft:ItemSpawnerEgg");
	NEI.hide("Thaumcraft:ItemLootBag");
	NEI.hide("Thaumcraft:blockArcaneFurnace");
	NEI.hide("Thaumcraft:blockWarded");
	NEI.hide("Thaumcraft:blockHole");
	NEI.hide("Thaumcraft:blockPortalEldritch");
	NEI.hide("Thaumcraft:blockEldritchNothing");
	NEI.hide("Thaumcraft:blockLootUrn");
	NEI.hide("Thaumcraft:blockLootCrate");
	NEI.hide("Thaumcraft:ItemEldritchObject");
	NEI.hide("Thaumcraft:*Cultist*");
	NEI.hide("Thaumcraft:ItemSwordCrimson");
	NEI.hide("Thaumcraft:blockMagicalLeaves");
	NEI.hide("Thaumcraft:blockFlux*");
	NEI.hide("Thaumcraft:blockTaintFibres");
	NEI.hide("Thaumcraft:blockArcaneDoor");
	NEI.hide("Thaumcraft:blockMagicBox");
	NEI.hide("Thaumcraft:blockAlchemyFurnace");
	NEI.hide("Thaumcraft:blockEldritch");
	NEI.hide("Thaumcraft:blockAiry");
	NEI.hide("Thaumcraft:blockManaPod");
	NEI.hide("thaumicenergistics:thaumicenergistics.block.essentia.vibration.chamber");
	NEI.override("thaumicenergistics:wireless.essentia.terminal", [0]);
	NEI.override("thaumicenergistics:storage.essentia", [0,1,2,3]);
	NEI.hide("ThaumicTinkerer:forcefield");
	NEI.hide("ThaumicTinkerer:nitorGas");
	NEI.hide("ThaumicTinkerer:gaseousShadow");
	NEI.hide("ThaumicTinkerer:bedrockPortal");
	NEI.hide("ThaumicTinkerer:gaseousLight");
	NEI.hide("ThaumicTinkerer:darkQuartzSlabFull");
	NEI.hide("ThaumicTinkerer:infusedGrainBlock");
	NEI.hide("ThaumicTinkerer:infusedFarmland");
}